name: flutter_riverpod_annotations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  random_name_generator: ^1.5.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
